"""
Token usage measurement for portfolio advisory graph.
Uses tiktoken if available, falls back to rough heuristic.
"""

# Try to import tiktoken
try:
    import tiktoken
    TIKTOKEN_AVAILABLE = True
    _ENCODER = tiktoken.get_encoding("cl100k_base")
except (ImportError, Exception):
    TIKTOKEN_AVAILABLE = False
    _ENCODER = None


def count_text_tokens(text: str) -> int:
    """
    Count tokens in text using tiktoken cl100k_base encoding.
    Falls back to rough heuristic (len/4) if tiktoken unavailable.
    
    Args:
        text: Text to count tokens for
        
    Returns:
        Estimated token count
    """
    if not text:
        return 0
    
    if TIKTOKEN_AVAILABLE and _ENCODER:
        try:
            return len(_ENCODER.encode(text))
        except Exception:
            # Fallback if encoding fails
            pass
    
    # Fallback heuristic: ~4 chars per token
    return max(1, len(text) // 4)


def add_node_usage(state: dict, node: str, prompt_text: str, output_text: str) -> None:
    """
    Measure and record token usage for a node execution.
    
    Args:
        state: Current state dictionary
        node: Name of the node
        prompt_text: Text that would be sent as prompt to LLM
        output_text: Text generated by the node
    """
    # Count tokens
    prompt_tokens = count_text_tokens(prompt_text)
    completion_tokens = count_text_tokens(output_text)
    total_tokens = prompt_tokens + completion_tokens
    
    # Initialize usage tracking if not present
    if "token_usage" not in state:
        state["token_usage"] = {
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "total_tokens": 0
        }
    
    if "token_trace" not in state:
        state["token_trace"] = []
    
    # Accumulate totals
    state["token_usage"]["prompt_tokens"] += prompt_tokens
    state["token_usage"]["completion_tokens"] += completion_tokens
    state["token_usage"]["total_tokens"] += total_tokens
    
    # Record trace entry
    state["token_trace"].append({
        "node": node,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens
    })
